### ISSUE TITLE
Документация по ПТК-ПСД

### ISSUE THREAD

**Issue by wermikulit** [diev/PTK-PSD-Browser-hta#10]
Дмитрий, день добрый! Очень нужна документация по ПТК-ПСД от разработчика. Из своего ГУ ЦБ мы смогли только получить комплект документов от 2011 года. "Свежее нет" сообщают нам. С Тулой они связаться не могут - как в черную дыру уходят вопросы.

Нашла ваш проект. Может, у вас есть что-то свежее?
Елена

**Comment by diev** [comment]
Некоторые новинки документации можно откопать в `\PTK PSD\FormList\help\` - туда сваливаются обновления документации, если того пожелают разработчики конкретных форм. А так у нас даже чистого дистрибутива долгое время не было, чтобы даже переустановить! Как начали в 2006(?), так и присылали много лет только обновления ставить поверх...

Напишите на diev # mail.ru - там будет проще общаться. С Наступающим! :)
